/*
 Copyright (c) 2013 Gildas Lormeau. All rights reserved.
 */
(function(){function q(a){function b(b){c.data?b():a.getData(new r,function(a){c.data=a;e=new v(a);b()},null,c.checkCrc32)}var c=this,e;c.size=0;c.init=function(b){this.size=a.uncompressedSize;b()};c.readUint8Array=function(a,c,h,d){b(function(){e.readUint8Array(a,c,h,d)},d)}}function z(a){function b(a){c+=a.uncompressedSize||0;a.children.forEach(b)}var c=0;b(a);return c}function w(a,b,c){function e(){d++;d<a.children.length?g(a.children[d]):b()}function g(a){a.directory?w(a,e,c):(a.reader=new a.Reader(a.data,
c),a.reader.init(function(){a.uncompressedSize=a.reader.size;e()}))}var d=0;a.children.length?g(a.children[d]):b()}function A(a){var b=a.parent.children;b.forEach(function(c,e){c.id==a.id&&b.splice(e,1)})}function F(a,b,c,e,d){function f(a,b,c,e,d){function g(){var p=b.children[B];p?a.add(p.getFullname(),p.reader,function(){h+=p.uncompressedSize||0;f(a,p,function(){B++;g()},e,d)},function(a){e&&e(h+a,d)},{directory:p.directory,version:p.zipVersion}):c()}var B=0;g()}var h=0;f(a,b,c,e,d)}function G(a,
b,c,e){function d(a,b){a.isDirectory&&a.createReader().readEntries(b);a.isFile&&b([])}function f(a,b,c){d(b,function(b){function d(b){function c(a){f(a,b,function(){k++;g()})}b.isDirectory&&c(a.addDirectory(b.name));b.isFile&&b.file(function(e){var d=a.addBlob(b.name,e);d.uncompressedSize=e.size;c(d)},e)}function g(){var a=b[k];a?d(a):c()}var k=0;g()})}b.isDirectory?f(a,b,c):b.file(function(e){a.addBlob(b.name,e);c()},e)}function H(a,b,c,e,d,f,h){function k(a,b,c,e,d,g){function f(b){function c(a){l+=
b.uncompressedSize||0;k(a,b,function(){n++;m()},e,d,g)}b.directory?a.getDirectory(b.name,{create:!0},c,d):a.getFile(b.name,{create:!0},function(a){b.getData(new zip.FileWriter(a,zip.getMimeType(b.name)),c,function(a){e&&e(l+a,g)},h)},d)}function m(){var a=b.children[n];a?f(a):c()}var n=0;m()}var l=0;b.directory?k(a,b,c,e,d,f):b.getData(new zip.FileWriter(a,zip.getMimeType(b.name)),c,e,h)}function t(a){a.entries=[];a.root=new m(a)}function I(a,b,c,e,d){function f(){var k=524288*h;e&&e(k,a.size);k<
a.size?a.readUint8Array(k,Math.min(524288,a.size-k),function(a){b.writeUint8Array(new Uint8Array(a),function(){h++;f()})},d):b.getData(c)}var h=0;f()}function J(a,b,c,e){var d=this;!a||a.constructor==d.Writer&&d.data?b(d.data):(d.reader||(d.reader=new d.Reader(d.data,e)),d.reader.init(function(){a.init(function(){I(d.reader,a,b,c,e)},e)}))}function n(a,b,c,e){if(a.directory)return e?new m(a.fs,b,c,a):new u(a.fs,b,c,a);throw"Parent entry is not a directory.";}function l(){}function u(a,b,c,e){l.prototype.init.call(this,
a,b,c,e);this.Reader=c.Reader;this.Writer=c.Writer;this.data=c.data;this.getData=c.getData||J}function m(a,b,c,e){l.prototype.init.call(this,a,b,c,e);this.directory=!0}function C(){t(this)}var x=zip.TextWriter,r=zip.BlobWriter,y=zip.Data64URIWriter,D=zip.TextReader,v=zip.BlobReader,E=zip.Data64URIReader,K=zip.createReader,L=zip.createWriter;q.prototype=new zip.Reader;q.prototype.constructor=q;q.prototype.checkCrc32=!1;l.prototype={init:function(a,b,c,e){if(a.root&&e&&e.getChildByName(b))throw"Entry filename already exists.";
c||(c={});this.fs=a;this.name=b;this.id=a.entries.length;this.parent=e;this.children=[];this.zipVersion=c.zipVersion||20;this.uncompressedSize=0;a.entries.push(this);e&&this.parent.children.push(this)},getFileEntry:function(a,b,c,e,d){var f=this;w(f,function(){H(a,f,b,c,e,z(f),d)},e)},moveTo:function(a){if(a.directory){if(a.isDescendantOf(this))throw"Entry is a ancestor of target entry.";if(this!=a){if(a.getChildByName(this.name))throw"Entry filename already exists.";A(this);this.parent=a;a.children.push(this)}}else throw"Target entry is not a directory.";
},getFullname:function(){for(var a=this.name,b=this.parent;b;)a=(b.name?b.name+"/":"")+a,b=b.parent;return a},isDescendantOf:function(a){for(var b=this.parent;b&&b.id!=a.id;)b=b.parent;return!!b}};l.prototype.constructor=l;var d;u.prototype=d=new l;d.constructor=u;d.getText=function(a,b,c,e){this.getData(new x(e),a,b,c)};d.getBlob=function(a,b,c,e){this.getData(new r(a),b,c,e)};d.getData64URI=function(a,b,c,e){this.getData(new y(a),b,c,e)};m.prototype=d=new l;d.constructor=m;d.addDirectory=function(a){return n(this,
a,null,!0)};d.addText=function(a,b){return n(this,a,{data:b,Reader:D,Writer:x})};d.addBlob=function(a,b){return n(this,a,{data:b,Reader:v,Writer:r})};d.addData64URI=function(a,b){return n(this,a,{data:b,Reader:E,Writer:y})};d.addFileEntry=function(a,b,c){G(this,a,b,c)};d.addData=function(a,b){return n(this,a,b)};d.importBlob=function(a,b,c){this.importZip(new v(a),b,c)};d.importText=function(a,b,c){this.importZip(new D(a),b,c)};d.importData64URI=function(a,b,c){this.importZip(new E(a),b,c)};d.exportBlob=
function(a,b,c){this.exportZip(new r("application/zip"),a,b,c)};d.exportText=function(a,b,c){this.exportZip(new x,a,b,c)};d.exportFileEntry=function(a,b,c,e){this.exportZip(new zip.FileWriter(a,"application/zip"),b,c,e)};d.exportData64URI=function(a,b,c){this.exportZip(new y("application/zip"),a,b,c)};d.importZip=function(a,b,c){var e=this;K(a,function(a){a.getEntries(function(a){a.forEach(function(a){var b=e,c=a.filename.split("/"),d=c.pop();c.forEach(function(a){b=b.getChildByName(a)||new m(e.fs,
a,null,b)});a.directory||n(b,d,{data:a,Reader:q})});b()})},c)};d.exportZip=function(a,b,c,d){var g=this;w(g,function(){L(a,function(a){F(a,g,function(){a.close(b)},c,z(g))},d)},d)};d.getChildByName=function(a){var b,c;for(b=0;b<this.children.length;b++)if(c=this.children[b],c.name==a)return c};C.prototype={remove:function(a){A(a);this.entries[a.id]=null},find:function(a){var b=a.split("/"),c=this.root;for(a=0;c&&a<b.length;a++)c=c.getChildByName(b[a]);return c},getById:function(a){return this.entries[a]},
importBlob:function(a,b,c){t(this);this.root.importBlob(a,b,c)},importText:function(a,b,c){t(this);this.root.importText(a,b,c)},importData64URI:function(a,b,c){t(this);this.root.importData64URI(a,b,c)},exportBlob:function(a,b,c){this.root.exportBlob(a,b,c)},exportText:function(a,b,c){this.root.exportText(a,b,c)},exportFileEntry:function(a,b,c,d){this.root.exportFileEntry(a,b,c,d)},exportData64URI:function(a,b,c){this.root.exportData64URI(a,b,c)}};zip.fs={FS:C,ZipDirectoryEntry:m,ZipFileEntry:u};zip.getMimeType=
function(){return"application/octet-stream"}})();